version: '2'
services:
    server:
        build: ./server/
        environment:
            - PYTHONUNBUFFERED=1 #to flush Python stdout else logs not displayed
            - ORIGIN=server
            - NUM_CLIENTS=1
    client1:
        build: ./client/
        environment:
            - ORIGIN=client1
        volumes:
            - ./all_data/saved_data_client_1:/usr/thisdocker/dataset:rw
    client2:
        build: ./client/
        environment:
            - ORIGIN=client2
        volumes:
            - ./all_data/saved_data_client_2:/usr/thisdocker/dataset:rw
#    client3:
#        build: ./client/
#        environment:
#            - ORIGIN=client3
#    client4:
#        build: ./client/
#        environment:
#            - ORIGIN=client4