version: '2'
services:
    node1:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node1
            - PEERS=['node2']
        volumes:
            - ./all_data/saved_data_client_1:/usr/thisdocker/dataset:rw
        privileged: true
        ports:
            - '5555'
        network_mode: none
        stdin_open: true
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
    node2:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node2
            - PEERS=[]
        volumes:
            - ./all_data/saved_data_client_2:/usr/thisdocker/dataset:rw
        privileged: true
        ports:
            - '5555'
        network_mode: none
        stdin_open: true
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
