version: '2'
services:
    node1:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node1
            - PEERS=[]
        volumes:
            - ./all_data/saved_data_client_1:/usr/thisdocker/dataset:rw
    node2:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node2
            - PEERS=[]
        volumes:
            - ./all_data/saved_data_client_2:/usr/thisdocker/dataset:rw
    node3:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node3
            - PEERS=[]
        volumes:
            - ./all_data/saved_data_client_3:/usr/thisdocker/dataset:rw
    node4:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node4
            - PEERS=[]
        volumes:
            - ./all_data/saved_data_client_4:/usr/thisdocker/dataset:rw
    node5:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node5
            - PEERS=[]
        volumes:
            - ./all_data/saved_data_client_5:/usr/thisdocker/dataset:rw
    node6:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node6
            - PEERS=[]
        volumes:
            - ./all_data/saved_data_client_6:/usr/thisdocker/dataset:rw
